### ISSUE TITLE
Garbled screen

### ISSUE THREAD

**Issue by tilleul** [ArthurFerreira2/reinetteIIe#1]
This is what I get when I start "reinette.exe" ... I get a CTRL-G beep then this ... Windows 10 21H1 ... should I install something else ?

![image](https://user-images.githubusercontent.com/3061106/125172224-c4fbcb00-e1b8-11eb-98cb-515a6942706c.png)

**Comment by ArthurFerreira2** [comment]
Actually on holiday, Try adding the following OpenGL attributes:

SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);

**Comment by ArthurFerreira2** [comment]
[reinette.zip](https://github.com/ArthurFerreira2/reinetteIIe/files/6839718/reinette.zip)

I compiled reinette with the above fix - please uncompress and replace the faulty reinette.exe by this one and report back

**Comment by tilleul** [comment]
This works ! Thx !

**Comment by ArthurFerreira2** [comment]
Thank you so much for the feedback :-)
